# Generated by Django 4.2 on 2023-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('vehicle_number', models.TextField()),
                ('is_available', models.IntegerField(choices=[(0, 'Available'), (1, 'In Use'), (2, 'Repair')], default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
