# Generated by Django 4.2 on 2023-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('description', models.TextField()),
                ('delievry_due', models.DateField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
