# Generated by Django 4.2 on 2023-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_delivered',
            field=models.IntegerField(choices=[(0, 'Not Delivered'), (1, 'Delivered'), (2, 'Processing')], default=0),
        ),
    ]
