# Generated by Django 4.2 on 2023-04-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0005_package_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='delievry_due',
            new_name='delivery_due',
        ),
    ]
