# Generated by Django 4.2 on 2023-04-10 12:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0006_rename_delievry_due_package_delivery_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='route',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='adminDB.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=False, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='vehicle',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='adminDB.vehicle'),
            preserve_default=False,
        ),
    ]
