# Generated by Django 4.2 on 2023-04-10 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0007_package_route_package_team_package_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='route',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminDB.route'),
        ),
        migrations.AlterField(
            model_name='package',
            name='team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=1, size=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='vehicle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminDB.vehicle'),
        ),
    ]
