# Generated by Django 4.2 on 2023-04-10 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0008_alter_package_route_alter_package_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
        ),
    ]
