# Generated by Django 4.2 on 2023-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDB', '0009_alter_package_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='team',
            field=models.TextField(),
        ),
    ]
